### ISSUE TITLE
Question: redis-rb-compatible DSL?

### ISSUE THREAD

**Issue by davidor** [socketry/protocol-redis#1]
I've seen that there's an effort to define a DSL with all the Redis commands in https://github.com/socketry/protocol-redis/tree/master/lib/protocol/redis/methods

The interface for some of those methods is not the same as the one provided by redis-rb.
For example, in redis-rb, `set` accepts an optional hash with `ex`, `px`, `nx`, and `xx`. In this project it's different https://github.com/socketry/protocol-redis/blob/cdbfb9b85dbc08b4a97569b11f11ec770db4a2c0/lib/protocol/redis/methods/strings.rb#L88

Also, there are methods like `exists` that return a boolean in redis-rb, whereas in this project they return '1' or '0'.

Of course, I'm not saying that's wrong. They're different projects and I understand that they might have chosen different interfaces. However, for users trying to migrate from redis-rb, having a compatible interface would simplify things.

My question is, are there any plans to offer that compatible DSL? If there are not, would you be willing to accept contributions?

**Comment by ioquatix** [comment]
PR welcome to improve compatibility. Please include documentation (i.e. `@return` annotations) where possible, but feel free to keep it minimal.

**Comment by ioquatix** [comment]
@huba do you mind commenting on your work regarding automating this from the JSON documentation? Maybe if you have time you could move that code to this repo?

**Comment by huba** [comment]
My automatic interface generation was just a quick and dirty script to wrap the `call` method so we know what to implement for a complete DSL. I only ever used it as a one-shot thing to generate placeholder methods (I realize this is not the best practice). See the [commit](https://github.com/socketry/async-redis/commit/7934dd83a77a97ac521b5ab2a942946b4f1527b7) in the `async-redis` gem, from before the async independent functionality was separated out into `protocol-redis`. Here is the [rake task](https://github.com/socketry/async-redis/blob/7934dd83a77a97ac521b5ab2a942946b4f1527b7/tasks/generate_dsl.rake)  that did it. I think the DSL methods that made the migration into this gem were implemented manually.

I suppose there is no reason why it can't be refined so it generates the interface with proper arguments.

**Comment by ioquatix** [comment]
To bring this issue to a close, I think there are the following points:

- We accept PRs to align compatibility.
- As far as compatibility is concerned, `call` is the ultimate entry point.
- An interface of your own creation can go via `call` in both this gem and `redis-rb`.

The only caveat is, I don't think we should make the interface in `protocol-redis` super complicated just for the sake of compatibility.

**Comment by ioquatix** [comment]
Regarding

> Also, there are methods like exists that return a boolean in redis-rb, whereas in this project they return '1' or '0'.

Let's definitely fix that. To me, boolean makes way more sense. Please consider making a PR.

**Comment by troex** [comment]
https://github.com/redis/redis-rb/blob/01768dab789c7f819fbbcdcec85802cbbcc83d5d/lib/redis.rb#L3417

redis-rb has nice lambdas that they pass to `call` method to get formatted results, which seams reasonable to avoid copy/paste or wrapping. However here `call` method as I understand is inside `async-redis` gem, so probably wrapping output with formatter method is better option.

@ioquatix do you have any ideas if redis-rb lambda idea could be applied here or how it would be better to implement common formatting methods? I have found some other methods which are not aligned with redis-rb

**Comment by ioquatix** [comment]
The protocol gem is supposed to be as agnostic as possible, i.e. implement the protocol.

I think for most use cases, you'd be better writing data structure wrappers, i.e. we could and have discussed introducing things like `Async::Redis::List`, `Async::Redis::Set`, in order to better hide these details.

I don't have any strong opinion about it, but I hesitate to introduce complexity which may benefit some users and hinder others. My general approach is layer-cake, so a formatter (or as outlined above, an actual data structure) probably makes the most sense.

Because handling the serialisation of rich data to Redis can be very much application specific - JSON, Marshal, MsgPack, etc all viable options.

**Comment by ioquatix** [comment]
By the way, regarding booleans, I don't mind that this gem handles that and returns true/false. But that needs to go both directions, and it needs to be absolutely certain that the interface can't return general integers for example.

**Comment by troex** [comment]
@ioquatix okay it makes sense, so if I understand correctly preferable place to pass or inject data wrappers would be somewhere around https://github.com/socketry/async-redis/blob/509ea5ee482e972b8db6e17b8dcdd5977ceec791/lib/async/redis/context/generic.rb#L52 this call, I think I'd ideally like to pass some wrapper to the instance as init parameter when it's created, am I going into the right direction?

**Comment by ioquatix** [comment]
Yes, I believe some data structure is more complex so it should wrap client - it may need to internally create transactions, etc. Other wrapper can just go directly around context.
