### ISSUE TITLE
Redis 6.2 ZRANGE compatibility

### ISSUE THREAD

**Issue by kriansa** [socketry/protocol-redis#14]
Starting with Redis 6.2.0, `ZRANGE` command can replace the following commands: ZREVRANGE, ZRANGEBYSCORE, ZREVRANGEBYSCORE, ZRANGEBYLEX and ZREVRANGEBYLEX.

> https://redis.io/commands/zrange

Currently, `zrange` only accepts `with_scores` as an option, and I think the compatibility fix should accept `by_score`, `by_lex` and `rev` as well.

**Comment by ioquatix** [comment]
Sorry, I missed this.

These methods are now all implemented.
